const i18Obj = {
  'en': {
    'skills': 'Skills',
    'portfolio': 'Portfolio',
    'video': 'Video',
    'price': 'Price',
    'contacts': 'Contacts',
    'en': 'en',
    'be': 'be',
    'hero-title': 'Alexa Rise',
    'hero-text': 'Save sincere emotions, romantic feelings and happy moments of life together with professional photographer Alexa Rise',
    'hire': 'Hire me',
    'skill-title-1': 'Digital photography',
    'skill-text-1': 'High-quality photos in the studio and on the nature',
    'skill-title-2': 'Video shooting',
    'skill-text-2': 'Capture your moments so that they always stay with you',
    'skill-title-3': 'Rotouch',
    'skill-text-3': 'I strive to make photography surpass reality',
    'skill-title-4': 'Audio',
    'skill-text-4': 'Professional sounds recording for video, advertising, portfolio',
    'winter': 'Winter',
    'spring': 'Spring',
    'summer': 'Summer',
    'autumn': 'Autumn',
    'standard': 'Standard',
    'premium': 'Premium',
    'gold': 'Gold',
    'price-description-1-span-1': 'One location',
    'price-description-1-span-2': '120 photos in color',
    'price-description-1-span-3': '12 photos in retouch',
    'price-description-1-span-4': 'Readiness 2-3 weeks',
    'price-description-1-span-5': 'Make up, visage',
    'price-description-2-span-1': 'One or two locations',
    'price-description-2-span-2': '200 photos in color',
    'price-description-2-span-3': '20 photos in retouch',
    'price-description-2-span-4': 'Readiness 1-2 weeks',
    'price-description-2-span-5': 'Make up, visage',
    'price-description-3-span-1': 'Three locations or more',
    'price-description-3-span-2': '300 photos in color',
    'price-description-3-span-3': '50 photos in retouch',
    'price-description-3-span-4': 'Readiness 1 week',
    'price-description-3-span-5': 'Make up, visage, hairstyle',
    'order': 'Order shooting',
    'contact-me': 'Contact me',
    'e-mail': 'E-mail',
    'phone': 'Phone',
    'message': 'Message',
    'send-message': 'Send message'
  },
  'be': {
    'skills': 'Навыкі',
    'portfolio': 'Партфоліё',
    'video': 'Відэа',
    'price': 'Кошты',
    'contacts': 'Кантакты',
    'en': 'анг',
    'be': 'бел',
    'hero-title': 'Алекса Райс',
    'hero-text': 'Захавайце шчырыя эмоцыі, рамантычныя перажыванні і шчаслівыя моманты жыцця разам з прафесійным фатографам',
    'hire': 'Запрасіць',
    'skill-title-1': 'Фатаграфія',
    'skill-text-1': 'Высакаякасныя фота ў студыі і на прыродзе',
    'skill-title-2': 'Відэаздымка',
    'skill-text-2': 'Запішыце лепшыя моманты, каб яны заўсёды заставаліся з вамі',
    'skill-title-3': 'Рэтуш',
    'skill-text-3': 'Я імкнуся да таго, каб фатаграфія пераўзыходзіла рэальнасць',
    'skill-title-4': 'Гук',
    'skill-text-4': 'Прафесійны запіс гуку для відэа, рэкламы, партфоліё',
    'winter': 'Зіма',
    'spring': 'Вясна',
    'summer': 'Лета',
    'autumn': 'Восень',
    'standard': 'Стандарт',
    'premium': 'Прэміум',
    'gold': 'Залаты',
    'price-description-1-span-1': 'Адна лакацыя',
    'price-description-1-span-2': '120 каляровых фота',
    'price-description-1-span-3': '12 адрэтушаваных фота',
    'price-description-1-span-4': 'Гатоўнасць праз 2-3 тыдні',
    'price-description-1-span-5': 'Макіяж, візаж',
    'price-description-2-span-1': 'Адна-дзве лакацыі',
    'price-description-2-span-2': '200 каляровых фота',
    'price-description-2-span-3': '20 адрэтушаваных фота',
    'price-description-2-span-4': 'Гатоўнасць праз 1-2 тыдні',
    'price-description-2-span-5': 'Макіяж, візаж',
    'price-description-3-span-1': 'Тры лакацыі і больш',
    'price-description-3-span-2': '300 каляровых фота',
    'price-description-3-span-3': '50 адрэтушаваных фота',
    'price-description-3-span-4': 'Гатоўнасць праз 1 тыдзень',
    'price-description-3-span-5': 'Макіяж, візаж, прычоска',
    'order': 'Замовіць здымку',
    'contact-me': 'Звяжыцеся са мной',
    'e-mail': 'Электронная пошта',
    'phone': 'Тэлефон',
    'message': 'Паведамленне',
    'send-message': 'Адправіць'
  }
}
export default i18Obj;